### ISSUE TITLE
Add support for Apple Silicon

### ISSUE THREAD

**Issue by TimOliver** [TimOliver/WebP-Cocoa#1]
For the life of me, [I could not get this library building for the new Apple Silicon for Mac architecture](https://github.com/TimOliver/WebP-Cocoa/blob/f95944be4c8c4ac9a5dbe5152a593f845ab1dbda/build.sh#L185).

Perhaps it's because I was trying to build this on macOS Catalina and not Big Sur, or perhaps (hopefully not) because running this build on Apple Silicon hardware is required.

In any case, if anyone knows more about this and could share this here, that would be amazing. :)

**Comment by deanPGM** [comment]
Hey @TimOliver ,

I've taken a look on the DTK and after uncommenting line 185 and changing `MacOSX` to `macosx`, it seems to compile fine into universal binaries. 

Line 185: `build_slice "arm64" "arm64-apple-macos11" "arm-apple-darwin" "macosx" ""`

Attached compiled frameworks below, which can be verified by running `lipo -info` on the binaries.

I've tested also on an Intel Mac running Big Sur beta 10 with Xcode 12.2 beta 2 and get the same output.
 
[macOS-DTK.zip](https://github.com/TimOliver/WebP-Cocoa/files/5398537/macOS-DTK.zip)

Hope this helps 😊🌶️

**Comment by TimOliver** [comment]
G'day @deanPGM!

Fantastic! That helped a tonne! 😁 Thank you so much for that! 

Okay then. I'll update the build script with your changes. And I just discovered that GitHub now supports running actions on Big Sur, so if I'll try and run it there.

Thanks again!

**Comment by TimOliver** [comment]
Woohoo! It's working! That did it! Thanks so much for your help @deanPGM! 😁

Hope you've doing well! Hope we can catch up again soon. Take care! 😊

**Comment by deanPGM** [comment]
Happy to help Tim, take care also 😊
